package com.myspace.argoz.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("ActionStatus")
public class ActionStatus implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("statusCode")
	private java.lang.String statusCode;

	public java.lang.String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(java.lang.String statusCode) {
		this.statusCode = statusCode;
	}

	public ActionStatus() {
	}

	public ActionStatus(java.lang.String statusCode) {
		this.statusCode = statusCode;
	}

}