package com.myspace.argoz.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Activity")
public class Activity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("advance")
	private java.lang.Integer advance;

	@org.kie.api.definition.type.Label(value = "actionManagementCode")
	private java.lang.String actionManagementCode;

	public Activity() {
	}

	public java.lang.Integer getAdvance() {
		return this.advance;
	}

	public void setAdvance(java.lang.Integer advance) {
		this.advance = advance;
	}

	public java.lang.String getActionManagementCode() {
		return this.actionManagementCode;
	}

	public void setActionManagementCode(java.lang.String actionManagementCode) {
		this.actionManagementCode = actionManagementCode;
	}

	public Activity(java.lang.Integer advance,
			java.lang.String actionManagementCode) {
		this.advance = advance;
		this.actionManagementCode = actionManagementCode;
	}

}