package com.myspace.argoz.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("AdvanceReport")
public class AdvanceReport implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("achievements")
	private java.lang.String achievements;
	@org.kie.api.definition.type.Label("actionCode")
	private java.lang.String actionCode;
	@org.kie.api.definition.type.Label("createdDate")
	private java.util.Date createdDate;
	@org.kie.api.definition.type.Label("difficulties")
	private java.lang.String difficulties;
	@org.kie.api.definition.type.Label("endDate")
	private java.util.Date endDate;
	@org.kie.api.definition.type.Label("number")
	private java.lang.String number;
	@org.kie.api.definition.type.Label("observations")
	private java.lang.String observations;
	@org.kie.api.definition.type.Label("startDate")
	private java.util.Date startDate;

	@org.kie.api.definition.type.Label("activities")
	private java.util.List<com.myspace.argoz.model.Activity> activities;

	@org.kie.api.definition.type.Label(value = "userSupervisor")
	private java.lang.String userSupervisor;

	public AdvanceReport() {
	}

	public java.lang.String getAchievements() {
		return this.achievements;
	}

	public void setAchievements(java.lang.String achievements) {
		this.achievements = achievements;
	}

	public java.lang.String getActionCode() {
		return this.actionCode;
	}

	public void setActionCode(java.lang.String actionCode) {
		this.actionCode = actionCode;
	}

	public java.util.Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(java.util.Date createdDate) {
		this.createdDate = createdDate;
	}

	public java.lang.String getDifficulties() {
		return this.difficulties;
	}

	public void setDifficulties(java.lang.String difficulties) {
		this.difficulties = difficulties;
	}

	public java.util.Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(java.util.Date endDate) {
		this.endDate = endDate;
	}

	public java.lang.String getNumber() {
		return this.number;
	}

	public void setNumber(java.lang.String number) {
		this.number = number;
	}

	public java.lang.String getObservations() {
		return this.observations;
	}

	public void setObservations(java.lang.String observations) {
		this.observations = observations;
	}

	public java.util.Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(java.util.Date startDate) {
		this.startDate = startDate;
	}

	public java.util.List<com.myspace.argoz.model.Activity> getActivities() {
		return this.activities;
	}

	public void setActivities(
			java.util.List<com.myspace.argoz.model.Activity> activities) {
		this.activities = activities;
	}

	public java.lang.String getUserSupervisor() {
		return this.userSupervisor;
	}

	public void setUserSupervisor(java.lang.String userSupervisor) {
		this.userSupervisor = userSupervisor;
	}

	public AdvanceReport(java.lang.String achievements,
			java.lang.String actionCode, java.util.Date createdDate,
			java.lang.String difficulties, java.util.Date endDate,
			java.lang.String number, java.lang.String observations,
			java.util.Date startDate,
			java.util.List<com.myspace.argoz.model.Activity> activities,
			java.lang.String userSupervisor) {
		this.achievements = achievements;
		this.actionCode = actionCode;
		this.createdDate = createdDate;
		this.difficulties = difficulties;
		this.endDate = endDate;
		this.number = number;
		this.observations = observations;
		this.startDate = startDate;
		this.activities = activities;
		this.userSupervisor = userSupervisor;
	}

}