package com.myspace.argoz.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Assignment")
public class Assignment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "notificationTime")
	private java.lang.String notificationTime;
	@org.kie.api.definition.type.Label(value = "escalationTime")
	private java.lang.String escalationTime;
	@org.kie.api.definition.type.Label(value = "escalationRole")
	private java.lang.String escalationRole;

	public Assignment() {
	}

	public java.lang.String getNotificationTime() {
		return this.notificationTime;
	}

	public void setNotificationTime(java.lang.String notificationTime) {
		this.notificationTime = notificationTime;
	}

	public java.lang.String getEscalationTime() {
		return this.escalationTime;
	}

	public void setEscalationTime(java.lang.String escalationTime) {
		this.escalationTime = escalationTime;
	}

	public java.lang.String getEscalationRole() {
		return this.escalationRole;
	}

	public void setEscalationRole(java.lang.String escalationRole) {
		this.escalationRole = escalationRole;
	}

	public Assignment(java.lang.String notificationTime,
			java.lang.String escalationTime, java.lang.String escalationRole) {
		this.notificationTime = notificationTime;
		this.escalationTime = escalationTime;
		this.escalationRole = escalationRole;
	}

}