package com.myspace.argoz.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Email")
public class Email implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Destinatario")
	private java.lang.String sendTo;
	@org.kie.api.definition.type.Label("Mensaje")
	private java.lang.String body;
	@org.kie.api.definition.type.Label("Asunto")
	private java.lang.String subject;

	public Email() {
	}

	public java.lang.String getSendTo() {
		return this.sendTo;
	}

	public void setSendTo(java.lang.String sendTo) {
		this.sendTo = sendTo;
	}

	public java.lang.String getBody() {
		return this.body;
	}

	public void setBody(java.lang.String body) {
		this.body = body;
	}

	public java.lang.String getSubject() {
		return this.subject;
	}

	public void setSubject(java.lang.String subject) {
		this.subject = subject;
	}

	public Email(java.lang.String sendTo, java.lang.String body,
			java.lang.String subject) {
		this.sendTo = sendTo;
		this.body = body;
		this.subject = subject;
	}

}