package com.myspace.argoz.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("GenericRequestDTO")
public class GenericRequestDTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("request")
	private java.lang.Object request;

	public GenericRequestDTO() {
	}

	public java.lang.Object getRequest() {
		return this.request;
	}

	public void setRequest(java.lang.Object request) {
		this.request = request;
	}

	public GenericRequestDTO(java.lang.Object request) {
		this.request = request;
	}

}