package com.myspace.argoz.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("MessageResponseDTO")
public class MessageResponseDTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Mensaje")
	private java.lang.String message;
	@org.kie.api.definition.type.Label("codigo respuesta")
	private Integer statusCode;
	@org.kie.api.definition.type.Label("objectResponse")
	private ObjectResponse objectResponse;

	public MessageResponseDTO() {
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public java.lang.Integer getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(java.lang.Integer statusCode) {
		this.statusCode = statusCode;
	}

	public com.myspace.argoz.model.ObjectResponse getObjectResponse() {
		return this.objectResponse;
	}

	public void setObjectResponse(
			com.myspace.argoz.model.ObjectResponse objectResponse) {
		this.objectResponse = objectResponse;
	}

	public MessageResponseDTO(java.lang.String message,
			java.lang.Integer statusCode,
			com.myspace.argoz.model.ObjectResponse objectResponse) {
		this.message = message;
		this.statusCode = statusCode;
		this.objectResponse = objectResponse;
	}

}