package com.myspace.argoz.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("ObjectResponse")
public class ObjectResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "number")
	private java.lang.String number;

	public ObjectResponse() {
	}

	public java.lang.String getNumber() {
		return this.number;
	}

	public void setNumber(java.lang.String number) {
		this.number = number;
	}

	public ObjectResponse(java.lang.String number) {
		this.number = number;
	}

}